# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Config-Universal
version:      0.3
version_from: lib/Config/Universal.pm
installdirs:  site
requires:
    HTTP::Request::Common:         
    HTTP::Response:                
    LWP::UserAgent:                
    XML::DOM:                      

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
